language: smalltalk

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-set-default

os:
  - linux
  - osx
  
smalltalk:
  - Pharo-6.1
  - Pharo64-6.1
  - Pharo64-7.0

env:
  matrix:
    - CI_FILE=.smalltalk.ston

script:
- travis_wait "$SMALLTALK_CI_HOME/run.sh" ${CI_FILE}
