language: smalltalk

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-set-default

os:
  - linux
  - osx
  
smalltalk:
  - Pharo-6.1

env:
  matrix:
    - CI_FILE=.smalltalk.ston

before_script:
- wget --quiet http://vdmpad.viennatalk.org/vdmj-3.2.0.jar -O $SMALLTALK_CI_BUILD/vdmj-3.2.0.jar
- wget --quiet http://vdmpad.viennatalk.org/Json4VDMJ.jar -O $SMALLTALK_CI_BUILD/Json4VDMJ.jar
    
script:
- travis_wait "$SMALLTALK_CI_HOME/run.sh" ${CI_FILE}
