Class {
	#name : #ViennaVDMFormatter,
	#superclass : #ViennaAbstractFormatter,
	#category : 'ViennaTalk-Parser-Core'
}

{ #category : #'symbol access' }
ViennaVDMFormatter >> and [
	^ 'and'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> bool [
	^ 'bool'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> concat [
	^ '^'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> dinter [
	^ 'dinter'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> domainRestrictedBy [
	^ '<-:'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> domainRestrictedTo [
	^ '<:'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> dot [
	^ '&'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> dots [
	^ '...'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> dunion [
	^ 'dunion'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> equiv [
	^ '<=>'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> exists [
	^ 'exists'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> exists1 [
	^ 'exists1'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> forall [
	^ 'forall'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> greaterThanOrEqual [
	^ '>='
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> imply [
	^ '=>'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> inmapInfix [
	^ 'to'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> inmapPrefix [
	^ 'inmap '
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> inset [
	^ 'in set'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> int [
	^ 'int'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> inter [
	^ 'inter'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> inversePostfix [
	^ ''
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> inversePrefix [
	^ 'inverse '
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> iota [
	^ 'iota'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> iterate [
	^ '**'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> lambda [
	^ 'lambda'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> lessThanOrEqual [
	^ '<='
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> mapInfix [
	^ 'to'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> mapPrefix [
	^ 'map '
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> maplet [
	^ '|->'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> mu [
	^ 'mu'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> mul [
	^ '*'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> munion [
	^ 'munion'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> nat [
	^ 'nat'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> nat1 [
	^ 'nat1'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> not [
	^ 'not'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> notEqual [
	^ '<>'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> notInSet [
	^ 'in set'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> oparrow [
	^ '==>'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> or [
	^ 'or'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> override [
	^ '++'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> partialFunction [
	^ '->'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> power [
	^ 'power'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> psubset [
	^ 'psubset'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> rangeRestrictedBy [
	^ ':->'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> rangeRestrictedTo [
	^ ':>'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> real [
	^ 'real'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> seq1Postfix [
	^ ''
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> seq1Prefix [
	^ 'seq1 of '
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> seqPostfix [
	^ ''
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> seqPrefix [
	^ 'seq of '
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> setDifference [
	^ '\'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> setPostfix [
	^ ''
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> setPrefix [
	^ 'set of'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> space [
	^ ' '
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> subset [
	^ 'subset'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> totalFunction [
	^ '+>'
]

{ #category : #'symbol access' }
ViennaVDMFormatter >> union [
	^ 'union'
]
