copyright notice
aboutVDMJ
	^ 'ViennaVDMJ uses VDMJ as an execution engine. 
Please note that VDMJ is copyrighted and licensed independent of ViennaTalk. 
Please visit the link below and the copyright notice for details.

VDMJ homepage: https://github.com/nickbattle/vdmj
/*******************************************************************************
 *
 *	Copyright (C) 2008-2013 Fujitsu Services Ltd.
 *
 *	Author: Nick Battle
 *
 *	VDMJ is free software: you can redistribute it and/or modify
 *	it under the terms of the GNU General Public License as published by
 *	the Free Software Foundation, either version 3 of the License, or
 *	(at your option) any later version.
 *
 *	VDMJ is distributed in the hope that it will be useful,
 *	but WITHOUT ANY WARRANTY; without even the implied warranty of
 *	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *	GNU General Public License for more details.
 *
 *	You should have received a copy of the GNU General Public License
 *	along with VDMJ.  If not, see .
 *
 ******************************************************************************/'