Class {
	#name : #ViennaImportFunctionsSignatureNode,
	#superclass : #ViennaImportSignatureNode,
	#type : #variable,
	#category : #'ViennaTalk-Parser-AST'
}

{ #category : #'as yet unclassified' }
ViennaImportFunctionsSignatureNode >> isViennaImportFunctionsSignatureNode [

	^ true
]

{ #category : #'as yet unclassified' }
ViennaImportFunctionsSignatureNode >> label [

	^ 'ImportFunctionsSignature'
]
