Class {
	#name : #ViennaImportOperationsSignatureNode,
	#superclass : #ViennaInterfaceComponentNode,
	#type : #variable,
	#category : #'ViennaTalk-Parser-AST'
}

{ #category : #'as yet unclassified' }
ViennaImportOperationsSignatureNode >> isViennaImportOperationsSignatureNode [

	^ true
]

{ #category : #'as yet unclassified' }
ViennaImportOperationsSignatureNode >> label [

	^ 'ImportOperationsSignature'
]
