remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ViennaTalk
description: Live and Formal
is_project_page: true
