remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ViennaTalk
description: Live and Formal
release: Waikiki
gihub:
  arm_mac_url: https://github.com/tomooda/ViennaTalk/releases/latest/download/viennatalk-mac-arm64.dmg
  intel_mac_url: https://github.com/tomooda/ViennaTalk/releases/latest/download/viennatalk-mac-x64.dmg
  linux_url: https://github.com/tomooda/ViennaTalk/releases/latest/download/viennatalk-linux-x64.dmg
  windows_url: https://github.com/tomooda/ViennaTalk/releases/latest/download/viennatalk-windows-x64.dmg
