name: CI
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'JavaScript/**'
      - 'Tutorials/**'
      - 'scripts/**'
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    strategy:
      matrix:
        include: # 32bit VM for windows platform because ProcessWrapper provides only 32bit DLL
          - os: ubuntu-latest
            smalltalk: Pharo64-9.0
          - os: macos-latest
            smalltalk: Pharo64-9.0
          - os: windows-latest
            smalltalk: Pharo32-9.0
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
        shell: bash
        timeout-minutes: 15
